[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DynamicExpressions = "a40a106e-89c9-4ca8-8020-a735e8728b6b"
Gumbo = "708ec375-b3d6-5a57-a7ce-8257bf98657a"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
SymbolicUtils = "d1185830-fcd6-423d-90d6-eec64667417b"

[compat]
Documenter = "0.27"
